insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(11, '上海教育集团', '上海教育集团', null, 1, 22, true, 'Group');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(1, '七宝中学教育集团', '上海教育集团-七宝中学教育集团', 11, 2, 11, true, 'Group');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(2, '上海市七宝中学', '七宝中学教育集团-上海市七宝中学', 1, 3, 4, true, 'School');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(3, '上海七宝德怀特高级中学', '七宝中学教育集团-上海七宝德怀特高级中学', 1, 5, 6, true, 'School');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(4, '上海市七宝xx小学', '七宝中学教育集团-上海市七宝xx小学', 1, 7, 8, true, 'School');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(5, '上海市七宝xx中学', '七宝中学教育集团-上海市七宝xx中学', 1, 9, 10, true, 'School');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(6, '上海徐汇教育集团', '上海教育集团-上海徐汇教育集团', 11, 12, 21, true, 'Group');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(7, '上海市徐家汇中学', '上海徐汇教育集团-上海市徐家汇中学', 6, 13, 14, true, 'School');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(8, '上海徐家汇xx高级中学', '上海徐汇教育集团-上海瑜伽会xx高级中学', 6, 15, 16, true, 'School');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(9, '上海市徐家汇xx小学', '上海徐汇教育集团-上海市徐家汇xx小学', 6, 17, 18, true, 'School');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(10, '上海市徐家汇xx中学', '上海徐汇教育集团-上海市徐家汇xx中学', 6, 19, 20, true, 'School');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(1, 'zhang','斯蒂芬','huang@gxcm.com','TRUE','女','18616949668','外部','9cbf8a4dcb8e30682b927f352d6559a0','店长','上海市-上海市-浦东新区','燕郊','篮球');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(2, 'dj','乐福','eisof@gxcm.com','TRUE','男','12584125412','内部','9cbf8a4dcb8e30682b927f352d6559a0','店长','上海市-上海市-徐汇区','燕郊','羽毛球');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(3, 'hiphop','科比','4585465581@qq.com','TRUE','女','18965412365','外部','7374ce58be384f97fb15117dd99fba3c','店长','河北省-三河市','燕郊','棒球');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(4, 'rnb','艾弗森','665848554@qq.com','TRUE','男','12345678912','内部','85862151eaed9bbc8b94373243e687cf','联采','河北省-三河市','燕郊','高尔夫');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(5, 'king','霍华德','dsea@gxcm.com','TRUE','男','12345678952','外部','74a0c18637d1c7585a37b331c78d71a8','联采','上海市-上海市-松江区','燕郊','排球');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(6, 'jason','哈登','dsf@gxcm.com','TRUE','男','12345874521','内部','9b476ed9ae35b34d43890d662bd1924a','联采','河北省-三河市','燕郊','铅球');
insert into cas_news(id,title,type,user_id) values(1,'hehe','slideshow','1');
insert into cas_news(id,title,type,user_id) values(2,'haha','slideshow','1');
insert into cas_news(id,title,type,user_id) values(3,'aaa','slideshow','1');
insert into cas_news(id,title,type,user_id) values(4,'bbb','listshow','1');
insert into cas_news(id,title,type,user_id) values(5,'ccc','listshow','1');
insert into cas_news(id,title,type,user_id) values(6,'ddd','listshow','1');
insert into cas_news(id,title,type,user_id) values(7,'eee','listshow','1');
insert into cas_store(id,store_name,address,phone,type,province) values(1,'a','a','1','slideshow','上海市');
insert into cas_store(id,store_name,address,phone,type,province) values(2,'b','b','2','slideshow','上海市');
insert into cas_store(id,store_name,address,phone,type,province) values(3,'c','c','3','listshow','上海市');
insert into cas_store(id,store_name,address,phone,type,province) values(4,'d','d','4','listshow','江苏省');
insert into cas_store(id,store_name,address,phone,type,province) values(5,'e','e','5','listshow','江苏省');
insert into CAS_USER_UNIT values(1,1);
insert into CAS_USER_UNIT values(1,2);
insert into CAS_USER_UNIT values(2,3);
insert into CAS_USER_UNIT values(2,4);
insert into CAS_USER_UNIT values(3,5);
insert into CAS_USER_UNIT values(3,6);
insert into CAS_USER_UNIT values(4,7);
insert into CAS_USER_UNIT values(5,8);
insert into CAS_USER_UNIT values(5,9);
insert into CAS_USER_UNIT values(6,10);