insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(1, '七宝中学教育集团', '七宝中学教育集团', null, 1, 8, true, 'Group');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(2, '上海市七宝中学', '上海市七宝中学', 1, 2, 5, true, 'School');
insert into cas_units(id, name, uri_name, parent_id, left_id, right_id, enable, category) values(3, '上海七宝德怀特高级中学', '上海七宝德怀特高级中学', 1, 6, 7, true, 'School');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(1, 'zhang','斯蒂芬','huang@gxcm.com','TRUE','女','18616949668','外部','9cbf8a4dcb8e30682b927f352d6559a0','河北省三河市','店长','燕郊','篮球');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(2, 'dj','发的','eisof@gxcm.com','TRUE','男','12584125412','内部','9cbf8a4dcb8e30682b927f352d6559a0','店长','河北省三河市','燕郊','羽毛球');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(3, 'hiphop','俄方的','4585465581@qq.com','TRUE','女','18965412365','外部','7374ce58be384f97fb15117dd99fba3c','店长','河北省三河市','燕郊','棒球');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(4, 'rnb','搞的','665848554@qq.com','TRUE','男','12345678912','内部','85862151eaed9bbc8b94373243e687cf','联采','河北省三河市','燕郊','高尔夫');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(5, 'king','范德萨','dsea@gxcm.com','TRUE','男','12345678952','外部','74a0c18637d1c7585a37b331c78d71a8','联采','河北省三河市','燕郊','排球');
insert into cas_users(id, code,name,email,enable,gender,mobile,category,password,position,location,address,notes)values(6, 'jason','额外','dsf@gxcm.com','TRUE','男','12345874521','内部','9b476ed9ae35b34d43890d662bd1924a','联采','河北省三河市','燕郊','铅球');
insert into cas_news(id,title,type,user_id) values(1,'hehe','slideshow','1');
insert into cas_news(id,title,type,user_id) values(2,'haha','slideshow','1');
insert into cas_news(id,title,type,user_id) values(3,'aaa','slideshow','1');
insert into cas_news(id,title,type,user_id) values(4,'bbb','listshow','1');
insert into cas_news(id,title,type,user_id) values(5,'ccc','listshow','1');
insert into cas_news(id,title,type,user_id) values(6,'ddd','listshow','1');
insert into cas_news(id,title,type,user_id) values(7,'eee','listshow','1');
insert into cas_store(id,store_name,address,phone,type) values(1,'a','a','1','slideshow');
insert into cas_store(id,store_name,address,phone,type) values(2,'b','b','2','slideshow');
insert into cas_store(id,store_name,address,phone,type) values(3,'c','c','3','listshow');
insert into cas_store(id,store_name,address,phone,type) values(4,'d','d','4','listshow');
insert into cas_store(id,store_name,address,phone,type) values(5,'e','e','5','listshow');
